# title: Akram El Assas - Senior Software Engineer
title: aelassas

remote_theme: jekyll/minima

google_analytics: G-9C49146FEV

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: classic
  
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/aelassas"
    - title: Linkedin
      icon: linkedin
      url: "https://www.linkedin.com/in/aelassas"
    - title: dev.to
      icon: dev
      url: "https://dev.to/aelassas"
