title: Akram El Assas - Senior Software Engineer

remote_theme: jekyll/minima

google_analytics: G-9C49146FEV

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: classic
  
  social_links:
    - { platform: github,         user_url: "https://github.com/aelassas" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/aelassas" }
    - { platform: devto,          user_url: "https://dev.to/aelassas" }
